name: Build
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  win-x64:
    name: Build (win-x64)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: ./build.cmd clr -c Release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: win-x64
          path: |
            artifacts/bin/coreclr/windows.x64.Release/coreclr.dll
            artifacts/bin/coreclr/windows.x64.Release/System.Private.CoreLib.dll
            artifacts/bin/coreclr/windows.x64.Release/clrjit.dll

  release:
    name: Create release
    if: github.ref_type == 'tag'
    needs: [ win-x64 ]
    runs-on: ubuntu-latest
    steps:
      - name: Download (win-x64)
        uses: actions/download-artifact@v4
        with:
          name: win-x64
          path: win-x64

      - name: Package
        run: |
          zip win-x64.zip win-x64/*

      - name: Release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
        with:
          files: |
            win-x64.zip
